IF DB_ID('MyDB') IS NOT NULL DROP DATABASE MyDB;

CREATE DATABASE MyDB;
GO

USE MyDB;
GO

IF OBJECT_ID('dbo.SKU', 'U') IS NOT NULL
DROP TABLE dbo.SKU;

IF OBJECT_ID('dbo.Family', 'U') IS NOT NULL
DROP TABLE dbo.Family;

IF OBJECT_ID('dbo.Basket', 'U') IS NOT NULL
DROP TABLE dbo.Basket;

CREATE TABLE dbo.SKU
(
  ID INT NOT NULL IDENTITY,
  Code AS ('s'+ CONVERT(NVARCHAR(15), ID)) UNIQUE,
  [Name] NVARCHAR(30) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE dbo.Family
(
  ID INT NOT NULL IDENTITY,
  SurName NVARCHAR(255) NOT NULL,
  BudgetValue DECIMAL(18, 2)  NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE dbo.Basket
(
  ID INT NOT NULL IDENTITY,
  ID_SKU INT NOT NULL,
  ID_Family INT NOT NULL,
  Quantity INT  NOT NULL CHECK (Quantity >= 0),
  [Value] DECIMAL(18, 2)  NOT NULL CHECK ([Value] >= 0),
  PurchaseDate DATETIME DEFAULT(SYSDATETIME()),
  DiscountValue DECIMAL(18, 2),
  PRIMARY KEY(ID),
  FOREIGN KEY (ID_SKU) REFERENCES dbo.SKU (ID),
  FOREIGN KEY (ID_Family) REFERENCES dbo.Family (ID)
);
GO
